services:
  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@hqswi7z2jql4dsef_high?TNS_ADMIN=/app/oracle_wallet
      - SPRING_RABBITMQ_HOST=rabbitmq_cn
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    restart: always
    networks:
      - rabbitmq_network
  rabbitmq_cn:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq_cn'
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_LOAD_DEFINITIONS=true
      - RABBITMQ_DEFINITIONS_FILE=/etc/rabbitmq/rabbit-definitions.json
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmq-data:/var/lib/rabbitmq
        - ./rabbit-definitions.json:/etc/rabbitmq/rabbit-definitions.json
    networks:
        - rabbitmq_network 

volumes:
  rabbitmq-data:
    driver: local

networks:
  rabbitmq_network:
    external: true